// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function none(param) {
  
}

function batch(cmds) {
  return function (make) {
    cmds.forEach(function (f) {
          return f(make);
        });
    
  };
}

export {
  none ,
  batch ,
  
}
/* No side effect */
