// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

var effect = {};

function getToken(name) {
  return Caml_array.caml_array_get(name.split("."), 0);
}

function register(token, manager) {
  effect[token] = manager;
  
}

export {
  effect ,
  getToken ,
  register ,
  
}
/* No side effect */
