// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function none(param) {
  return [];
}

function map(fn, msg) {
  return /* Cmd */{
          _0: Curry._1(fn, msg._0)
        };
}

var Cmd = {
  none: none,
  map: map
};

function none$1(param) {
  return [];
}

function map$1(fn, msg) {
  return /* Sub */{
          _0: Curry._1(fn, msg._0)
        };
}

var Sub = {
  none: none$1,
  map: map$1
};

function useReducerT(config) {
  var update = config.update;
  var update$1 = React.useCallback((function (state) {
          return function (action) {
            return Curry._2(update, state[0], action);
          };
        }), [update]);
  React.useEffect((function () {
          console.log(123);
          
        }), [config.sub]);
  var match = React.useReducer(Curry.__2(update$1), config.init);
  var match$1 = match[0];
  React.useEffect((function () {
          console.log(123);
          
        }), [match$1[1]]);
  return [
          match$1[0],
          match[1]
        ];
}

export {
  Cmd ,
  Sub ,
  useReducerT ,
  
}
/* react Not a pure module */
