// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function delay(ctor, delay$1) {
  return function (make) {
    var match = Curry._1(make, undefined);
    var fulfil = match[0];
    var id = setTimeout((function (param) {
            return fulfil(Curry._1(ctor, undefined));
          }), delay$1);
    return Curry._1(match[1], (function (param) {
                  clearTimeout(id);
                  
                }));
  };
}

function delayFloat(ctor, delay) {
  return function (make) {
    var match = Curry._1(make, undefined);
    var fulfil = match[0];
    var id = setTimeout((function (param) {
            return fulfil(Curry._1(ctor, undefined));
          }), delay);
    return Curry._1(match[1], (function (param) {
                  clearTimeout(id);
                  
                }));
  };
}

function nextFrame(ctor) {
  return function (make) {
    var match = Curry._1(make, undefined);
    var fulfil = match[0];
    var id = requestAnimationFrame(function (time) {
          return fulfil(Curry._1(ctor, time));
        });
    return Curry._1(match[1], (function (param) {
                  cancelAnimationFrame(id);
                  
                }));
  };
}

var every = 10;

var everyFloat = 10.0;

export {
  delay ,
  delayFloat ,
  nextFrame ,
  every ,
  everyFloat ,
  
}
/* No side effect */
