// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function $$delete(_dict, _key) {
  return (delete dict[key]);
}

var Dict = {
  $$delete: $$delete
};

export {
  Dict ,
  
}
/* No side effect */
